### ISSUE TITLE
[Feat] 유저 토너먼트 전적 페이지 레이아웃

### ISSUE THREAD

**Issue by greatSweetMango** [42organization/42gg.client#1068]
## Desc

유저 토너먼트 전적 페이지의 기본적인 레이아웃을 잡습니다.

## Detail

페이지 타이틀 / 배경 / 리그 선택 버튼과, 우승자 프로필을 보여주는 슬라이드뷰 및 각 토너먼트 별 브래킷뷰가 들어갈 레이아웃을 구성합니다.

## Todo
- [ ] 페이지 타이틀 및 배경
- [ ] 리그 선택 버튼
- [ ] 우승자 슬라이드 뷰 컨테이너 및 우승자 정보
- [ ] 브래킷 뷰 컨테이너
