### ISSUE TITLE
[Feat] 유저 토너먼트 전적 페이지 우승자 스와이프 뷰

### ISSUE THREAD

**Issue by Clearsu** [42organization/42gg.client#1070]
## Desc

스와이프하여 우승자 프로필을 탐색할 수 있는 스와이프 뷰
## Detail

좌 / 우측으로 스와이프하여 우승자 프로필을 확인할 수 있는 스와이프 뷰를 만듭니다.
가운데에는 현재 정보를 볼 수 있는 우승자 프로필이 위치하고, 좌측 / 우측으로 순서대로 z-index가 낮아져 앞의 유저 프로필에 의해 가려지게 됩니다.
아래는 UI 디자인입니다.
<img width="403" alt="image" src="https://github.com/42organization/42gg.client/assets/67998022/efb0f211-a275-4e3f-b025-295e2566b0a4">

## Todo
- [x] 스와이프하여 다음 유저 탐색
- [x] 순서에 따른 프로필 이미지 z-index 및 사이즈 조정
- [x] 스와이프 시 애니메이션 적용
