### ISSUE TITLE
[Feat] 토너먼트 게임 정보 Mock API

### ISSUE THREAD

**Issue by greatSweetMango** [42organization/42gg.client#1102]
## Desc

토너먼트 브래킷 뷰를 그리기 위한 게임의 인터페이스와 Mock API를 작성합니다.
## Detail

API에 맞는 인터페이스와 브래킷 뷰에 필요한 인터페이스를 따로 제작합니다.
## Todo
- [ ] 토너먼트 게임 인터페이스
- [ ] 토너먼트 브래킷뷰 인터페이스
- [ ] 토너먼트 게임 전체 조회 Mock API
