### ISSUE TITLE
[Feat] 관리자 토너먼트 페이지 유저 수정 모달 UI 및 API 연동

### ISSUE THREAD

**Issue by Clearsu** [42organization/42gg.client#1134]
## Desc

유저 수정 모달을 완성합니다.

## Todo
- [ ] 참가자 및 대기자 구분 UI
- [ ] 유저 추가 API
- [ ] 유저 삭제 API
