### ISSUE TITLE
[Feat] 유저 페이지 레이아웃 구성

### ISSUE THREAD

**Issue by yoouyeon** [42organization/42gg.client#1243]
### Description

유저 페이지 라우팅, 레이아웃 구성

### Todo

- [x] 모집 페이지 라우팅 설정
- [x] 모집 페이지 레이아웃 설정
- [x] 공고 있을 경우 사이드바 버튼 추가
