### ISSUE TITLE
[Feat] 공고 페이지 레이아웃 구성

### ISSUE THREAD

**Issue by parksangmin1543** [42organization/42gg.client#1246]
### Description

공고 페이지 레이아웃 구성

### Todo

- [ ] 공고페이지 레이아웃 구성
- [ ] 공고페이지 지원자 레이아웃 구성
- [ ] 공고페이지 알림 레이아웃 구성
