### ISSUE TITLE
[Feat] Party모집 서비스의 메인 페이지 구현

### ISSUE THREAD

**Issue by izone00** [42organization/42gg.client#1280]
## Desc

Party모집 서비스의 메인 페이지 구현
## Detail

Party모집의 첫 화면으로 내가 참여한 파티나 전체 파티 목록리스트를 조회하는 목적의 페이지입니다.
예상 디자인
<img width="300" alt="Screen Shot 2024-03-11 at 3 58 18 PM" src="https://github.com/42organization/42gg.client/assets/91773764/052f649f-0bdf-43fd-bad1-fde0bc0e02cf">

## Todo
- [x] 프로필 띄우기 (폐지)
- [x] 내가 참여한 파티 리스트
- [x] 파티 검색
- [x] 파티 생성 버튼
- [x] 전체 파티 리스트 조회
- [x] 파티 카테고리 필터링

## Etc
- 3.1까지 완성
