### ISSUE TITLE
[Feat] Party모집 방 생성 페이지 구현

### ISSUE THREAD

**Issue by izone00** [42organization/42gg.client#1281]
## Desc

파티 모집 방 생성페이지 구현
## Detail

- 파티의 카테고리를 설정
- 파티의 카테고리에는 미리 작성된 템플릿을 고를 수 있습니다.
- 마지막으로 템플릿을 커스텀할수 있습니다.
<img width="600" alt="Screen Shot 2024-03-11 at 4 00 58 PM" src="https://github.com/42organization/42gg.client/assets/91773764/284e6396-b679-4585-a40b-5abb344e1c39">

## Todo
- [x] 카테고리 선택 버튼
- [x] 템플릿 선택 버튼 및 템플릿 자동완성
- [x] 방 정보 상세 수정 페이지
- [x] validation

## Etc
- 모달 사용여부는 구현해보고 결정
- 3.12까지 완성
