### ISSUE TITLE
[Feat] Party모집 상세 페이지 작성

### ISSUE THREAD

**Issue by contemplation-person** [42organization/42gg.client#1283]
## Detail
<img width="181" alt="Screen Shot 2024-03-11 at 4 40 47 PM" src="https://github.com/42organization/42gg.client/assets/68673565/f620aa2c-9eb3-46c2-b489-1784ce318d12">

방의 디테일 한 내용을 알려주는 기능을 하며, 신고, 댓글, 방 참여 등 기능이 있습니다.

## Todo
- [x]  참여 버튼 완성
- [x]  조인 버튼 완성
- [x]  떠나기 버튼 완성
- [x]  시작하기 버튼 완성
- [x]  신고 기능
- [x]  공유하기 기능
- [x]  댓글 기능
- [x]  상세 내역 띄우기
- [x]  commentBox 컴포넌트 분리
- [x]  commentCreateBar 컴포넌트 분리
- [x] #1294
- [x] 버튼 css적용
- [x] 뒷 배경 css적용
