### ISSUE TITLE
[Feat] 지원 결과 상태 추가

### ISSUE THREAD

**Issue by yoouyeon** [42organization/42gg.client#1305]
## Description
- 지원 결과 확인 api 변경사항 반영

## Todo
- [x] 공고 상세 조회 데이터에 `applicationId` 추가
- [x] 지원한 경우 지원하기 버튼 비활성화
- [x] 지원 결과 확인 api url 수정
- [x] 지원 상태 추가 (`null`,  `PROGRESS`, `APPLICATION_FAIL`, `INTERVIEW`, `PASS`, `INTERVIEW_FAIL`)
- [x] `APPLICATION_FAIL`인 경우 progress 2단계로 수정
