### ISSUE TITLE
[Feat] 파티 어드민 페이지에 패널티 신고 페이지 구현 

### ISSUE THREAD

**Issue by mantoing** [42organization/42gg.client#1309]
## Desc

파티 기능의 패널티를 관리하기 위한 파티 패널티 어드민 구현
## Todo
- [ ]  파티 패널티 조회 페이지 구현
- [ ]  추가 기능 만들기
- [ ]  변경 기능 만들기
- [ ]  삭제 기능 만들기

**Comment by greatSweetMango** [comment]
기존에 관리자 패널티 페이지가 있는데 따로 만들어야 할 이유가 있나요??

**Comment by mantoing** [comment]
저희도  처음에 그렇게 생각했는데 백쪽에서 분리해야할거같다고 해서 요청에 의해 만들었습니다.

**Comment by greatSweetMango** [comment]
> 저희도 처음에 그렇게 생각했는데 백쪽에서 분리해야할거같다고 해서 요청에 의해 만들었습니다.

패널티 관리탭에 카테고리를 나누는 건가요??

**Comment by mantoing** [comment]
어 아뇨 그 파티관련 어드민 페이지를 따로만들고 거기 안에서 관리하려고 하고있습니다.
