### ISSUE TITLE
[Feat] party detail room의 css 변경

### ISSUE THREAD

**Issue by contemplation-person** [42organization/42gg.client#1358]
contemplation-person

## Desc

버튼 크기 조절, 경고 margin 제거, hr 투명도 추가

## Detail

css 변경

## Todo
- [x] 버튼 크기 조절
- [x] 경고 이미지에 margin 지우기
- [x] hr에 투명도 추가
- [x] comment creator에 글자 폰트 색 진하게 보여주기
