### ISSUE TITLE
[Feat] agenda list 레이아웃

### ISSUE THREAD

**Issue by siwolee** [42organization/42gg.client#1437]
## Desc

- agenda page UI를 제작합니다. 
## Detail
- 모바일 레이아웃을 먼저 제작 후, 웹 버전의 레이아웃을 제작 할 예정입니다.

## Todo
- [x] 웹, 모바일 버전 레이아웃 확정하기
- [x] agenda list 컴포넌트 UI 만들기 / 모바일 버전
- [ ] agenda list 컴포넌트 UI 만들기 / 웹 버전

**Comment by siwolee** [comment]
웹 UI는 따로 진행하겠습니다
