### ISSUE TITLE
[Feat] admin 페이지 레이아웃

### ISSUE THREAD

**Issue by irenee-14** [42organization/42gg.client#1456]
## Desc

- agenda 관리 페이지 레이아웃

## Todo
- [x] 대회 조회(대회, 상태, 참여인원 확인)
- [ ] 대회 승인요청 확인
- [ ] 대회/팀 강제 취소
- [x] 팀 조회

**Comment by nerdchanii** [comment]
#1500 #1510 에서 해결된 것같아 이슈를 클로즈합니다. 아직 논의가 더 필요한 이슈로 생각되시면 이슈를 다시 재오픈시켜주세요.
