### ISSUE TITLE
[Feat] Profile 페이지 API호출

### ISSUE THREAD

**Issue by JeongRon** [42organization/42gg.client#1469]
## Desc

- Profile 페이지에 필요한 API 호출
- Profile 페이지 UI 개선
## Detail

- Profile Page API
   - GET / 개인 상세 조회 
   - GET / 참여중 대회
   - GET / 참여했던 대회
   - GET / 프로필 이미지, Acheivement (intra API)
   - PATCH / 프로필 수정
## Todo
- [x] API GET (개인 상세 조회, 참여중인 대회, 참여했던 대회)
- [x] API PATCH (프로필 수정)
- [x] 권한별(나, 상대방)에 따른 프로필 수정 버튼
- [x] 프로필 수정 시, 에러 발생 → 모달창 띄우기 (모달창 만들어지면 추가)
- [x] API GET / 
- [x] 유저 프로필 검색 기능
- [x] 프로필 이미지, Acheivement 데이터 intra에서 가져오기 (백엔드 완성 시 작업)

**Comment by siwolee** [comment]
정론님 이거 다 됀 부분인지 한번 확인 부탁드려요 @JeongRon
