### ISSUE TITLE
[Feat] agenda list api 연결

### ISSUE THREAD

**Issue by siwolee** [42organization/42gg.client#1479]
## Desc

agenda 전체 리스트 api 연결

## Todo
- [ ] 대회 현황 전체 조회
- [ ] 대회 생성하기 (개인, 비공식)
- [ ] 지난 대회 보기
- [ ] 내 팀 간단 조회
