### ISSUE TITLE
[Feat] 남은 페이지(index, ticket) 만들기

### ISSUE THREAD

**Issue by siwolee** [42organization/42gg.client#1484]
## Desc

몇 페이지 안남았습니다

## Detail

index 페이지: 탁구 바로가기, 매치 비워두기
ticket : api까지 테스트 할수있으면 하기

## Todo
- [ ] index UI
- [ ] index api (전체 대회 리스트)
- [ ] ticket UI
- [ ] ticket api 연결
- [ ] tickt 발급 테스트
