### ISSUE TITLE
[Feat] usePageNation반영 / 버그 / css

### ISSUE THREAD

**Issue by siwolee** [42organization/42gg.client#1498]
## Desc

기존 api중 페이지네이션 사용하는 api에 totalSize가 추가됨 / usePageNation 제작 완료로 반영 필요
또한 버그 css 필요

## Detail

버그 : useEffect가 반복해서 쓰이는 듯 화면 떨림 현상
css : 글씨체 등 반영 안되어 있어 추가 필요함

## Todo
- [ ] css 아젠다 용으로 분리
- [ ] 버그 픽스
---
- [ ] 지난 대회 보기
- [x] 공지사항 전체조회
- [x] 내가 참여했던 대회
- [ ] 내가 개최중인 대회 (백엔드 제작중, 대기 필요)
- [ ] 내가 개최했던 대회 (백엔드 제작중, 대기 필요)
- [x] 모집중인 팀
- [x] 확정된 팀
