### ISSUE TITLE
[Style] CSS 스타일 개선

### ISSUE THREAD

**Issue by JeongRon** [42organization/42gg.client#1570]
## Desc

- 아젠다 CSS 개선

## Todo

- [x] 개행 처리 기능 추가 / 대회 설명, 공지사항 내용 작성 -> 개행 처리 안되어 있는 것 개선
- [x] index 첫 페이지 / 버튼 클릭 모션 개선, 모집 중 아젠다 없을 시 UI 개선
- [x] 프로필 페이지 / 아젠다 프로필 카드 개선 (업적 설명 마우스 hover처리)
- [x] 프로필 페이지 / 아젠다 리스트 UI 개선 (내 프로필 아닐 시-  참여중 안보이게 개선)
