### ISSUE TITLE
[Meet] 외부 디자이너와 미팅

### ISSUE THREAD

**Issue by mike2ox** [42organization/42gg.client#605]
## DESC
- 디자인 시안 및 피드백을 위한 외부 디자이너와의 미팅

## TODO
- [x] 장소, 일정, 참석자 조율
- [x] 42gg 서비스 안내
- [x] 컨셉 공유
- [x] 일정 공유
- [x] 합류 fix due 합의

## REF
- [와이어프레임](https://www.figma.com/file/sf7prt6NLaKQxc0jtbPPfO/42gg?node-id=0%3A1&t=Oi54nToId64R6yk2-0)
- [컨셉](https://www.figma.com/file/gJVqP211Ujt3jgHy6u27ko/42gg-design?node-id=0%3A1&t=BkiqyjrB8vSYgRxL-0)
- [회의록](https://ruby-motorcycle-99b.notion.site/4-w-a4636de9750645e981e1b029b2106a60)
