### ISSUE TITLE
[Bug] 여러 디바이스에서 접근시 관리페이지 결과물이 각각 다름

### ISSUE THREAD

**Issue by mike2ox** [42organization/42gg.client#609]
## DESC
- 관리자 계정으로 여러 디바이스에서 접근시 관리 페이지는 한 곳에서만 열람

## TODO
- [x] 프론트쪽 관리자 페이지 코드 확인
- [x] 백엔드쪽 관리자 페이지 접근 로직 확인
- [x] 관리자 페이지 열람 규정 논의된 것 존재 확인(1기 회의록)

## ETC
- 인가/인증 단계에서 문제가 있는 것으로 추측됩니다.
- 데이터 무결성을 위해 관리자(혹은 유저도 포함)가 로그인 한다면 기존에 연결되있던 클라이언트에서 접근하려 할 시 Error를 제공하면 어떨까 싶습니다.

**Comment by mike2ox** [comment]
## RESULT
- 현재 백엔드에서 직접 관리자페이지를 만들어서 쏴주는 플로우로 유저 검증을 진행(by nheo)
- 관리자 페이지를 프론트에서 직접하면 위 문제가 해결될 것으로 예상
