### ISSUE TITLE
[Feat]  Searchbar 최근검색기록

### ISSUE THREAD

**Issue by 42sungwook** [42organization/42gg.client#610]
## DESC
현재 onfocus될 때 keyword를 같이 받아야 dropdown을 보여주는데 
keyword를 받지 않을 때는 최근검색기록을 보여주는 기능이 있어도 좋을 것 같습니다

## TODO
- [ ] 이 기능을 추가할지에 대한 논의
- [ ] 최근검색기록 local storage에 저장
- [ ] keyword가 없을 때 최근검색기록 불러오는 기능 추가

## ETC
추가적인 기능으로 최근검색기록 목록 삭제도 고려해볼 수 있을 것 같습니다.
