### ISSUE TITLE
[Feat] 프론트 관리자 페이지 레이아웃 생성

### ISSUE THREAD

**Issue by raehy19** [42organization/42gg.client#621]
## Desc

23년 1월 27일 기준 api 명세와 디자인 바탕으로 관리자 페이지 생성

## Detail

관리자 권한만 접근 가능한 관리자 페이지 생성
좌측 네비게이션바 추가
네비게이션바 페이지 라우팅 추가

## Todo
- [x] 관리자 권한만 접근 가능한 관리자 페이지 생성
- [x] 좌측 네비게이션바 추가
- [x] 네비게이션바 페이지 라우팅 추가
