### ISSUE TITLE
[Feat] 관리자 페이지 테이블 템플릿 구현

### ISSUE THREAD

**Issue by mike2ox** [42organization/42gg.client#623]
## Desc

- 관리자 페이지에서 내부 내역에 보여줄 테이블 템플릿 개발

## Detail

- 화면에 최대 20명만 보여주는 식으로 구성
- 버튼 컴포넌트가 최소 1개씩은 들어갈 예정

## Todo
- [x] MUI 디자인 시스템 적용하기
- [x] 페이지네이션 적용
- [x] 검색결과 테이블에 적용하기

## Etc
- 필터링 기능은 추후 기수에서 진행

**Comment by mike2ox** [comment]
## Etc
- 공용 테이블을 만들려 했으나 시간대비 결과물이 바로 안나와서 고유 테이블을 각각 만들기로 결정
- MVP2-2 작업하면서 공용 테이블로 업데이트 고려

**Comment by mike2ox** [comment]
## 추가 사항

- [ ] 디자인 시안에 맞게 스타일 적용
- [ ] cell 안에 내용이 길 경우 `자세히` 버튼 제공
- [ ] `자세히` 내용 보는 방식 추가하기(modal or expand content)
- [ ] 공용 컴포넌트로 빼기

**Comment by mike2ox** [comment]
##
