### ISSUE TITLE
[Feat] 패널티, 알림 mock api 제작

### ISSUE THREAD

**Issue by mike2ox** [42organization/42gg.client#626]
## Desc

- 패널티, 알림(notification)관련 mock api 세팅

## Detail

- 백엔드와 협의한 api spec에 맞춰서 mock data 구성
- Next.js의 기본 기능 이용

## Todo
- [x] 전송한 알림 전체 조회
- [x] 특정 유저 알림 전송
- [x] 전체 알림 전송
- [x] 패널티 상세 정보 조회
- [x] 패널티 전체 조회
- [x] 패널티 삭제
- [x] 패널티 유저명 검색 조회

## Etc
- 패널티 유저명 검색조회가 필요한지 BE담당자와 미팅 필요
