### ISSUE TITLE
[Fix] 관리자 피드백 확인 모달 api요청

### ISSUE THREAD

**Issue by 42sungwook** [42organization/42gg.client#642]
## Desc
api post 요청시 body 정보에 id 필요

## Detail
피드백 확인 모달에서 post 요청을 보낼 때 body에 피드백 id가 들어있어서 해당 데이터를 넣어 요청을 보내도록 수정 필요

## Todo
- [x] id를 어디서 받아오는지 확인
- [x] 해당 id를 post 요청할 때 body에 넣어 요청
- [x] api 요청이 잘 가는지 확인
