### ISSUE TITLE
[Feat] 유저 프로필 모달 개선

### ISSUE THREAD

**Issue by 42sungwook** [42organization/42gg.client#647]
## Desc
관리자 유저 모달에서 발생되는 문제점 해결

## Detail
type, 초기값 설정 등 문제점 해결

## Todo
- [x] 버튼 클릭 영역 수정
- [x] inputHandler타입 문제 해결
- [x] userInfo 초기값 설정
- [x] number 형태의 데이터만 따로 처리해주는 eventHandler 제작
- [x] 숫자가 없을 때 NaN표시 -> 0으로 수정
- [x] import 순서 맞추기
- [x] 불변성 유지하는 방법이 여러가지가 있는데 [참고](https://leehwarang.github.io/docs/tech/2020-03-15-object.html)
- [x] image 태그 alt 채우기 [참고](https://hi-seo.co.kr/seo-contents/seo-%EC%BD%98%ED%85%90%EC%B8%A0-%EC%B5%9C%EC%A0%81%ED%99%94/alt-%ED%83%9C%EA%B7%B8%EC%9D%98-%EC%A4%91%EC%9A%94%EC%84%B1%EA%B3%BC-%EC%9E%91%EC%84%B1-%EB%85%B8%ED%95%98%EC%9A%B0/)
- [x] Props 타입명 수정
- [x] userInfo 타입 ''을 null로 수정 -> **HTMLInputElement는 null타입이 없고 num, string, ..., undefined 형식만 존재**
- [x] statusMessage 30자로 제한

## Etc
[PR 참고할것](https://github.com/42organization/42gg.client/pull/645)
