### ISSUE TITLE
[Feat] loading, error component 제대로 적용하기

### ISSUE THREAD

**Issue by mike2ox** [42organization/42gg.client#656]
## Desc

- data fetching 중 유저에게 보여줄 loading, error 로직 설정 및 UI 제작

## Detail

- data fetching 중 지연, 오작동을 안내해주기 위해 loading, error page(또는 component) 제작
- react-query로 isLoading, isError를 파악해서 보여줄 수 있으나 기술 이전은 추후에 진행

## Todo
- [x] axios interceptor 공식문서 확인
- [x] 자체 Loading, Error 컴포넌트 디자인 or mui 사용할지 검토

## Etc
- Next.js의 getStaticPaths 를 사용해서 SSR, ISR 설정을 통해 Next.js 기능 극대화할 것

**Comment by mike2ox** [comment]
## 추가사항
- [ ] 기본적인 get외의 method일 때 toast로 성공, 실패(케이스별) 알려주기
