### ISSUE TITLE
[Feat] search bar 기능 업데이트

### ISSUE THREAD

**Issue by mike2ox** [42organization/42gg.client#657]
## Desc

- 실제 검색 사이트에 있는 검색 창과 동일한 동작하도록 업데이트

## Detail

- 완전한 intra id가 아니더라도 일부 매칭되는 키워드를 키보드 조작(상하)으로 선택 가능하도록
- 검색 입력부에서 enter시 검색이 되도록
- 최근 검색 기록 보여주기(#610 참고)

## Todo
- [x] 기존 searchBar 구조 파악하기
- [ ] API 데이터 전송 형태 파악(갯수, 관련 검색어를 찾아주는 BE 조건)
- [ ] searchBar 추가 기능 적용

## Etc
- 일부만 완성되도 배포하기

**Comment by mike2ox** [comment]
## Done
- 3기 진행하면서 searchBar의 기능이 업데이트 됨
