### ISSUE TITLE
[Feat] 유저 모달 에러 관리

### ISSUE THREAD

**Issue by 42sungwook** [42organization/42gg.client#666]
## Desc
이미지 압축기능 추가
토스트로 오류 처리 (아직 토스트가 완성되지 않아서 주석으로 처리)
여러가지 에러 처리

## Detail
- 정보가 수정되지 않았을 때 보내는 방식 수정
   - 이미지는 수정되지 않으면 폼데이터에서 제거
   - 이미지 제외 모든 정보는 수정 여부에 상관없이 폼데이터에 추가
- 에러 수정
   - 404 에러 수정 (유저 이미지 초기값이 null인 상태로 렌더링하여 띄워주려해서 생긴 현상)
   - 이미지 정보를 받아도 모달에 뜨지 않는 현상 해결
     (이미지 태그의 width, height 값이 실제 이미지 크기보다 작아서 생김 -> 압축으로 크기 지정)
- 압축 기능 추가
   - browser-image-compression 라이브러리를 사용하는데 에러 발생 해결
      (현재 custom hook으로 파일 업로드를 따로 빼서 관리하는데 export하는 함수에 async를 제거하여 해결)
   - 압축하고 보내는데 타입 관련해서 문제가 지속적으로 발생 해결
      (압축된 imgData를 제대로 보내지 않아 생긴 문제)
- 에러 상태 수정 
   (200 정상, 207 랭크정보만 없어서 수정 불가, 400 잘못된 요청, 401 권한 없음, 413 파일 용량제한 에러, 415 파일 확장자 에러)
   - 토스트 메시지로 처리
- 프로필 이미지가 없는 경우
   - 현재 유저에게 보여지는 프로필은 돔의 규격에 맞지 않으면 다스베이더를 보여줍니다
      하지만 관리자에게 다스베이더를 보여줄 필요는 없다고 판단하여 alt 메세지 수정
      관리자가 이미지를 바꿔주면 이미지 압축을 맞게 해주어 문제 없을 것으로 판단 (사용자가 보는 프로필 이미지는 다시 확인 필요) 
## Todo
- [x] 관리자 롤 변경 안됨 현상 확인
- [x] 이미지 수정하지 않았을 때 어떻게 보내지는지 확인
- [ ] 정의된 에러 상태 토스트 메시지로 관리
