### ISSUE TITLE
[Feat] 관리자 특정 유저 알림 모달 추가

### ISSUE THREAD

**Issue by Wilbur0306** [42organization/42gg.client#669]
## Desc

관리자 페이지의 특정 유저 알림 모달 관련 to do list 
## Detail

관리자 페이지 특정 유저 알림 모달 기능 추가 및 toast message 붙이기

## Todo
- [x] [기능] 관리자 페이지 특정 유저 알림 모달 만들기
- [x] [기능] 관리자 페이지 특정 유저 알림 모달에 toast message 붙이기
- [x] [CSS] 관리자 페이지 디자인/시안과 통일 시키기
- [x] [API] API 관련 작업하기
- [x] [기능] 상단의 모든 작업 완료 후 관리자 "알림 관리" 페이지와 연결시키기
