### ISSUE TITLE
[Others] 슬랙 알림 봇 구현

### ISSUE THREAD

**Issue by mike2ox** [42organization/42gg.client#670]
## Desc

- notification 관련 슬랙 봇 구현

## Detail

- 기존 email로 안내되던 매칭 안내 알림을 slack 봇을 통해서 알림 보내주기

## Todo
- [x] 담당자 확정 및 일정 산출
- [x] 슬랙 알림 봇 공식 문서 학습
- [x] test 슬랙 워크스페이스에서 확인
- [x] 폴베님께 봇 등록 요청하기
- [x] 유저 프로필 수정에서 막혀있는 버튼 수정

## Etc

- 3월 관리자 페이지 정식 배포전에 완료해야 함
- 유저 프로필에서 알림을 받을지 말지를 선택할 수 있어야함(#616)
- BE 담당자 : @wken5577

**Comment by mike2ox** [comment]
## 확인사항
- 슬랙봇 접수가 완료된 상황이고 빠르면 일주일 길면 6개월 대기라 전달받음
- 슬랙봇 생성이 완료가 되기전까지 해당 이슈는 열어둘 예쩡
