### ISSUE TITLE
[Feat] 스케쥴러 UI 변경 및 리팩토링

### ISSUE THREAD

**Issue by 42sungwook** [42organization/42gg.client#696]
## Desc
14회 정식 회의로 바뀐 내용 적용 및 코드 리팩토링

## Detail
- 과거 noSlot들은 보여지지 않는 것으로 수정
- 과거 시간은 0~3만 입력값으로 받게 수정
- 미래 시간은 1~23만 입력값으로 받게 수정
- 미래 시간은 현재 스케쥴러에 적용되있는 미래 시간보다 줄어들어도 보이는 슬롯은 줄이지 않게 변경
  (실제 적용할 때 미래 슬롯을 잡아놓는 유저가 있을 경우 발생하는 문제로 변경)
- 게임 시간 60에서 나눴을 때 나눠 떨어지는지 기준으로 적용 (15, 30, 60분 보다 더 많은 게임시간 받을 수 있도록)

## Todo
- [ ] 과거 noSlot 보이지 않게 수정
- [ ] 과거/미래 시간 min/max 수정
- [ ] 게임시간 60에서 나눴을 때 나눠 떨어지는 수만 input으로 받게 변경
- [ ] CSS 적용
