### ISSUE TITLE
[Feat] infinity scroll 수정

### ISSUE THREAD

**Issue by 42sungwook** [42organization/42gg.client#771]
## Desc

infinity scroll에서 api요청할 때 페이지 번호로 수정

## Detail

game 페이지, rank 페이지에서 동일한 api를 요청하고 있는데 
game 페이지에서는 game id 로 요청하고 
rank 페이지에서는 페이지 번호로 요청을 하고 있습니다.
백엔드쪽에서는 불필요한 로직이어서 삭제하신다고 하여 저희도 api 요청할 때 수정이 필요합니다!

## Todo
- [ ] /pingpong/games?seasonId=${seasonId}&gameId=${gameId}&count=${pageSize}&status=${gameStatus}&mode=${gameMode} api 수정 확인
- [ ] api에 맞게 /game 부분 api 요청 부분 변경
- [ ] api 요청 테스트
