### ISSUE TITLE
[Others] Cypress를 이용한 테스트 추가

### ISSUE THREAD

**Issue by yoouyeon** [42organization/42gg.client#772]
## Desc

- Cypress 사용을 위한 설정
- 테스트 케이스별 테스트 코드 추가

## Detail
Cypress 사용을 위한 초기 설정을 하고, 미리 정의한 테스트케이스대로 테스트 코드 추가하려고 합니다. (테스트케이스 : 노션 회의록 참고)

## Todo
- [ ] Cypress 설정
- [ ] Profile 페이지 테스트코드 추가
- [ ] Game 페이지 테스트 코드 추가
- [ ] Header 메뉴 테스트 코드 추가
- [ ] 게임 매칭 과정 테스트 코드 추가
